### ISSUE TITLE
unable to use label with add subommand

### ISSUE THREAD

**Issue by TheTaoOfPhil** [chaosteil/doist#111]
Greetings,

Per the examples on the README file, I gather that it should be possible to apply a label to a new task. 

For example: 

```
doist add "my test task"  -d "today" -p 3  -L blck_seq_mrng  -P "chrs" 
created task: 7918691307 p3 my test task today @blck_seq_mrng [chrs]
```

The task is indeed created with the correct name and priority and project. And the feedback message from doist suggests that the label was applied. However, when I subsequently run the following command, the new task does not show up:

```
doist list -f  @blck_seq_mrng
```

Similarly, the task shows up in the web application, but without the label.

I tried boiling the command down to the bare minimum like in the examples, as follows: 

```
doist add "minimal task" --label blck_seq_mrng
```

I got the same result.

It also occurred to me that perhaps using underscores or a long label name might be causing a problem, so I created a label called ``shortlabel``. I repeated the experiment above and got the same result. 

Am I doing something wrong or misunderstood something about the command line arguments? 

Thanks!

**Comment by chaosteil** [comment]
I think there has been an API regression that the tool didn't follow. Will fix this up soon, thanks for the report!

**Comment by chaosteil** [comment]
Should be in v0.2.7!
