### ISSUE TITLE
project list

### ISSUE THREAD

**Issue by ecocode** [chaosteil/doist#25]
Can you add a command to list all projects ?  Eventually also filtering out projects without open tasks ?

**Comment by chaosteil** [comment]
Heyo! There's `doist projects list`, but I've not thought of a filter like that, let me think of something!

**Comment by chaosteil** [comment]
I'm thinking of something like:
```
doist list -P project_name
```
to filter for all open tasks of a project in addition to the `-f` filter. Eventually I hope to make `doist projects list` more interactive so you can browse tasks directly by going there (in addition to renaming projects or adding comments to them)

I'm still thinking of a good UX to not show projects that don't have any open tasks, let me get back to you here.

**Comment by chaosteil** [comment]
With 0.1.14 you can now do `doist l -f all -P name` to get all tasks under a project (or use a different filter), and the same with `-S section` and `-L label` for labels, so you can set this all up like you need it. Still thinking about the UX for
> projects with open tasks
but I think I'm getting there.

**Comment by chaosteil** [comment]
Okay with 0.1.16 there's now a feature to do filters on the project list, #32 has some details in the comment. Cheers! In general more interactivity in the projects list is still planned (listing tasks of the selected project for instance)

**Comment by ecocode** [comment]
thanks !
