### ISSUE TITLE
Releases/Tags

### ISSUE THREAD

**Issue by sadikkuzu** [chaosteil/doist#56]
Hi @chaosteil 
Is it possible to tag these "Release X.Y.Z" commits with "vX.Y.Z"?
(and/or in [Release](https://github.com/chaosteil/doist/releases) section)

https://github.com/chaosteil/doist/commit/06c777eb18bfbf8760f307525ae2596ec7b08220

**Comment by chaosteil** [comment]
Sure it is! Let me go a bit through the history here

**Comment by chaosteil** [comment]
All done! I will do a proper release pipeline at some point, still have some things I want to work out first.
