### ISSUE TITLE
feat: change default filter in config

### ISSUE THREAD

**Issue by samyosm** [chaosteil/doist#95]
It would be lovely if there were a way of changing the default filter (currently `(today | overdue)`). The easiest way of achieving this would be via the config.yml file.

**Comment by samyosm** [comment]
I would love to do it but I haven't yet learned Rust. But I believe the starting point to be in the following lines:
1. https://github.com/chaosteil/doist/blob/62933890abac05e82918f536bf39efac3432a66c/src/tasks/filter.rs#L10-L17
2. https://github.com/chaosteil/doist/blob/62933890abac05e82918f536bf39efac3432a66c/src/config.rs#L16-L31

**Comment by chaosteil** [comment]
Sure that seems doable, let me see if I can whip it up real quick and I'll make a new release.

**Comment by chaosteil** [comment]
And 0.2.2 is out. Enjoy!
