### ISSUE TITLE
Editing date gives invalid response

### ISSUE THREAD

**Issue by chaosteil** [chaosteil/doist#99]
Was trying to update date for a task:
```
New value: 2023-05-08 09:00:00 PST
Error:
   0: unable to update task
   1: unable to parse API response
   2: invalid type: map, expected a string at line 1 column 0

Location:
   .../src/api/rest/gateway.rs:306
```

This should probably give a more reasonable and readable response, and possibly not even error out

**Comment by nisargparikh69** [comment]
@chaosteil 
Can you update your README or Issue description about editing Task? 
README has only steps for adding task / viewing task / closing task, but not Editing !

**Comment by chaosteil** [comment]
@nisargparikh69 Absolutely, I'll be happy to! Easiest way is to just edit in the interactive menu when you select a task. I'll make a new task for documenting the editing.
